Repository intuit/design-systems-cli, pull requests merged in 2020-09, with the labels that each got.

#478 print storybook build error
  plugins/storybook/src/index.ts
Labels: patch

#479 use my addon-notes replacement
  plugins/storybook/.storybook/preset.js
  plugins/storybook/package.json
  renovate.json
  yarn.lock
Labels: patch

#490 add css optimization level flag
  plugins/build/src/command.ts
  plugins/build/src/index.ts
Labels: minor

#491 increase max number of lint warnings default
  plugins/lint/src/command.ts
Labels: patch

#492 still print warnings if they are present
  plugins/lint/src/utils/lintUtils.ts
Labels: patch

#487 Multi-Build CSS & CSS ESM Imports
  .eslintrc
  packages/babel-plugin-replace-styles/README.md
  packages/babel-plugin-replace-styles/jest.config.js
  packages/babel-plugin-replace-styles/package.json
  packages/babel-plugin-replace-styles/src/__tests__/exists.test.ts
  packages/babel-plugin-replace-styles/src/__tests__/helpers/utils.ts
  packages/babel-plugin-replace-styles/src/__tests__/index.test.ts
  packages/babel-plugin-replace-styles/src/exists.ts
  packages/babel-plugin-replace-styles/src/index.ts
  packages/babel-plugin-replace-styles/tsconfig.json
  packages/load-config/src/index.ts
  plugins/build/src/command.ts
  plugins/build/src/index.ts
  plugins/build/src/postcss.ts
  plugins/build/src/typescript.ts
Labels: do-not-merge, minor

#509 add postcss group
  renovate.json
Labels: internal

#511 add autoprefixer to renovate postcss config
  renovate.json
Labels: internal

#515 Add utils from our design system
  jest.config.js
  packages/utils/README.md
  packages/utils/jest.config.js
  packages/utils/package.json
  packages/utils/src/index.tsx
  packages/utils/src/utils/__tests__/__snapshots__/createInstanceIfDefined.test.tsx.snap
  packages/utils/src/utils/__tests__/__snapshots__/createSlots.test.tsx.snap
  packages/utils/src/utils/__tests__/__snapshots__/styled.test.tsx.snap
  packages/utils/src/utils/__tests__/createInstanceIfDefined.test.tsx
  packages/utils/src/utils/__tests__/createSlots.test.tsx
  packages/utils/src/utils/__tests__/debounce.test.ts
  packages/utils/src/utils/__tests__/displayName.test.tsx
  packages/utils/src/utils/__tests__/getProp.test.tsx
  packages/utils/src/utils/__tests__/isReactInstanceOf.test.tsx
  packages/utils/src/utils/__tests__/logger.test.ts
  packages/utils/src/utils/__tests__/omit.test.ts
  packages/utils/src/utils/__tests__/portal.test.tsx
  packages/utils/src/utils/__tests__/styled.test.tsx
  packages/utils/src/utils/arrayify.ts
  packages/utils/src/utils/createInstanceIfDefined.tsx
  packages/utils/src/utils/createSlots.tsx
  packages/utils/src/utils/debounce.ts
  packages/utils/src/utils/displayName.ts
  packages/utils/src/utils/focus-lock.tsx
  packages/utils/src/utils/fromEntries.ts
  packages/utils/src/utils/getProp.ts
  packages/utils/src/utils/isReactInstanceOf.ts
  packages/utils/src/utils/logger.ts
  packages/utils/src/utils/omit.ts
  packages/utils/src/utils/portal.tsx
  packages/utils/src/utils/styled.tsx
  packages/utils/tsconfig.json
  tsconfig.build.json
  typings/focus-lock.d.ts
  yarn.lock
Labels: minor

#514 Only generate .js file mappings for the main css output
  plugins/build/src/index.ts
  plugins/build/src/postcss.ts
Labels: bug, patch

#524 update displayName type
  packages/utils/src/utils/displayName.ts
Labels: patch
