Repository intuit/design-systems-cli, pull requests merged in 2020-04, with the labels that each got.

#192 breaking down index into multiple files + utils
  plugins/size/src/RelativeCommentsPlugin.ts
  plugins/size/src/index.ts
  plugins/size/src/interfaces.ts
  plugins/size/src/undefined.ts
  plugins/size/src/utils/CalcSizeUtils.ts
  plugins/size/src/utils/DiffUtils.ts
  plugins/size/src/utils/WebpackUtils.ts
  plugins/size/src/utils/formatUtils.ts
Labels: internal

#195 replace escaped curly braces in templates
  packages/create/src/copy.ts
Labels: patch

#196 Loosen Proof version range
  plugins/proof/package.json
  yarn.lock
Labels: patch

#197 update proof in storybook plugin too
  plugins/storybook/package.json
Labels: patch

#198 remove applitools dep in proof plugin
  plugins/proof/package.json
  yarn.lock
Labels: patch

#204 feat: adding feature to auto assign a port
  plugins/storybook/package.json
  plugins/storybook/src/command.ts
  plugins/storybook/src/index.ts
  typings/find-free-port.d.ts
  yarn.lock
Labels: minor

#211 docs: fix typo in annotate.md
  packages/docs/src/advanced/annotate.md
Labels: documentation

#210 docs: update getting started canary release guide
  packages/docs/src/getting-started.md
Labels: documentation

#212 Update only desired babel config
  plugins/storybook/.storybook/config.js
  plugins/storybook/.storybook/webpack.config.js
Labels: patch

#213 Enable storybook middleware
  plugins/storybook/.storybook/middleware.js
  plugins/storybook/src/command.ts
Labels: minor

#214 Move story/snippet/test type-checking to respective plugins
  plugins/build/src/command.ts
  plugins/build/src/typescript.ts
  plugins/dev/package.json
  plugins/dev/src/command.ts
  plugins/dev/src/index.ts
  plugins/playroom/package.json
  plugins/playroom/src/playroom.config.ts
  plugins/storybook/.storybook/webpack.config.js
  plugins/storybook/package.json
  plugins/storybook/src/index.ts
  yarn.lock
Labels: minor
