Repository intuit/design-systems-cli, pull requests merged in 2020-02, with the labels that each got.

#134 Add install step to getting started
  packages/docs/src/getting-started.md
Labels: documentation, skip-release

#135 Copy Images to dist
  plugins/build/src/command.ts
  plugins/build/src/index.ts
Labels: minor

#136 Support Non-Monorepo Package Root
  packages/cli-utils/src/utils/get-repo-root.ts
  packages/cli-utils/src/utils/index.ts
  plugins/bundle/src/index.ts
Labels: patch

#138 Add arg to set the top-level destination folder for components and packages
  packages/create/src/cli.ts
  packages/create/src/run.ts
Labels: minor

#139 changing log level from debug to info for sauce url
  plugins/proof/proof.config.base.js
Labels: patch

#140 renaming from TEP to Connection
  plugins/proof/proof.config.base.js
Labels: patch

#141 update package template
  packages/create/README.md
  packages/create/src/templates.json
Labels: patch
