Repository intuit/design-systems-cli, pull requests merged in 2020-10, with the labels that each got.

#528 Fix/issues 523 tsc is not recognized
  README.md
  package.json
Labels: patch

#540 feat(readme): overview
  README.md
Labels: documentation

#538 Create GitHub action to format using prettier
  action.yml
  package.json
  yarn.lock
Labels: internal

#552 add Next.js plugin to allow CSS imports for components build with 'ds build'
  packages/next-esm-css/README.md
  packages/next-esm-css/jest.config.js
  packages/next-esm-css/package.json
  packages/next-esm-css/src/index.js
  packages/next-esm-css/tsconfig.json
  scripts/template-plugin/package.json
Labels: minor

#557 Improve ReadMe #532 #hacktoberfest
  README.md
Labels: documentation

#558 fix: issue committing on windows
  packages/create/src/run.ts
Labels: patch

#577 allowing more then one Component to be passed in to styled
  packages/utils/README.md
  packages/utils/src/utils/styled.tsx
Labels: minor

#579 move postcss-themed reloading into postcss-themed package
  plugins/storybook/.storybook/modify-webpack.js
Labels: patch

#580 fix css source map generation
  plugins/build/src/index.ts
Labels: patch

#581 loosen babel dep ranges
  packages/babel-plugin-include-styles/package.json
  packages/babel-plugin-replace-styles/package.json
  packages/next-esm-css/package.json
  packages/utils/package.json
  plugins/build/package.json
  plugins/playroom/package.json
  plugins/proof/package.json
  plugins/storybook/package.json
  plugins/test/package.json
  renovate.json
  yarn.lock
Labels: patch

#583 adds jsx to jest moduleFileExtension list
  plugins/test/src/jest.config.base.ts
Labels: patch
