Repository intuit/design-systems-cli, pull requests merged in 2020-06, with the labels that each got.

#264 Update jest monorepo
  package.json
  plugins/build/package.json
  plugins/test/package.json
  yarn.lock
Labels: dependency-update

#265 Update linters
  packages/cli-utils/src/create-logger.ts
  packages/eslint-config/package.json
  plugins/lint/package.json
  plugins/playroom/src/snippets.ts
  plugins/test/src/jest/setupTests.ts
  yarn.lock
Labels: dependency-update

#269 Upgrade Ts eslint
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/plugin/src/index.ts
  plugins/bundle/src/webpack.base.config.ts
  plugins/lint/src/utils/lintUtils.ts
  plugins/playroom/src/playroom.config.ts
  plugins/playroom/src/snippets.ts
  plugins/test/src/jest/setupTests.ts
  yarn.lock
Labels: dependency-update

#270 Upgrade to storybook 6.0
  packages/plugin/src/index.ts
  plugins/lint/src/utils/lintUtils.ts
  plugins/storybook/.storybook/addons-preset.js
  plugins/storybook/.storybook/defaultConfig.js
  plugins/storybook/.storybook/middleware.js
  plugins/storybook/.storybook/modify-webpack.js
  plugins/storybook/.storybook/preset.js
  plugins/storybook/.storybook/presets.js
  plugins/storybook/.storybook/preview.js
  plugins/storybook/README.md
  plugins/storybook/package.json
  plugins/storybook/preset.js
  plugins/storybook/preview.js
  plugins/storybook/src/command.ts
  plugins/storybook/src/index.ts
  yarn.lock
Labels: major

#271 Fix more storybook 6.0 bugs
  plugins/storybook/.storybook/modify-webpack.js
  plugins/storybook/.storybook/preset.js
  plugins/storybook/.storybook/preview.js
  plugins/storybook/package.json
  plugins/storybook/src/index.ts
  yarn.lock
Labels: patch

#272 Fix more storybook 6.0 bugs
  plugins/storybook/.storybook/modify-webpack.js
  plugins/storybook/.storybook/preset.js
Labels: patch

#273 don't type-check snippets during build
  plugins/build/src/typescript.ts
Labels: patch

#274 use a better globbing library
  plugins/storybook/.storybook/preset.js
  plugins/storybook/package.json
Labels: patch

#275 feat: adding ability to send failure threshold from args
  plugins/size/src/command.ts
  plugins/size/src/index.ts
  plugins/size/src/interfaces.ts
  yarn.lock
Labels: minor

#276 fix ignoring files during watch mode
  plugins/build/src/index.ts
Labels: patch

#277 only load source maps for packages in monorepo
  plugins/storybook/.storybook/modify-webpack.js
Labels: patch

#278 exclude node_modules
  plugins/storybook/.storybook/modify-webpack.js
Labels: patch

#279 Completely ignore some files in typescript build
  plugins/build/src/typescript.ts
Labels: patch

#280 update storybook deps
  plugins/storybook/package.json
  yarn.lock
Labels: patch

#281 don't build and files in a `stories/` folder
  plugins/build/src/command.ts
Labels: patch

#282 upgrade storybook
  plugins/storybook/package.json
  yarn.lock
Labels: patch

#283 lint mdx files
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  plugins/lint/src/utils/lintUtils.ts
  yarn.lock
Labels: minor
