Repository intuit/design-systems-cli, pull requests merged in 2020-01, with the labels that each got.

#1 fix: typo, README link
  README.md
  packages/docs/src/getting-started.md
Labels: documentation

#3 Release v1 :champagne: :ship:
  README.md
  packages/cli/README.md
  packages/docs/src/faq.md
  packages/docs/src/getting-started.md
  packages/docs/src/index.html
  packages/docs/src/usage.md
Labels: major

#4 fix publishing
  README.md
  package.json
  yarn.lock
Labels: internal

#5 correct kendall
  .all-contributorsrc
  README.md
  plugins/test/src/index.ts
Labels: documentation

#8 upgrade command-line-application
  packages/cli/package.json
  packages/create/package.json
  packages/plugin/package.json
  yarn.lock
Labels: patch

#9 add clearer docs around custom storybook config
  plugins/storybook/src/command.ts
Labels: patch

#10 use correct changelog link
  plugins/update/src/index.ts
Labels: patch

#11 merge user supplied args so they don't get overwritten
  packages/cli/package.json
  packages/cli/src/cli.ts
Labels: patch, skip-release

#12 ignore building/copying mdx files
  plugins/build/src/command.ts
Labels: patch

#13 Hash the classnames based on the contents of the css file + selector + package.json
  .npmrc
  plugins/build/package.json
  plugins/build/src/configs/postcss.config.ts
  yarn.lock
Labels: bug, patch

#14 log proof error
  plugins/proof/src/index.ts
Labels: patch

#15 add size option for private registry
  .circleci/config.yml
  plugins/lint/src/index.ts
  plugins/size/src/command.ts
  plugins/size/src/index.ts
Labels: minor

#16 Update renovate.json
  renovate.json
Labels: internal, skip-release

#21 Update label
  package.json
Labels: internal, skip-release

#26 Update renovate.json
  renovate.json
Labels: internal, skip-release

#27 Update renovate.json
  renovate.json
Labels: internal, skip-release

#28 Update renovate.json
  renovate.json
Labels: internal, skip-release

#34 upgrade storybook
  plugins/storybook/package.json
  yarn.lock
Labels: patch

#45 Update renovate.json
  renovate.json
Labels: internal, skip-release

#62 group eslint
  renovate.json
Labels: internal, skip-release

#74 add stylelint group
  renovate.json
Labels: internal, skip-release

#98 1 PR per update
  renovate.json
Labels: internal, skip-release

#102 Run renovate monthly
  renovate.json
Labels: internal, skip-release

#103 update some thing for storybook 5.3
  plugins/storybook/.storybook/addons-preset.js
  plugins/storybook/.storybook/webpack.config.js
Labels: patch

#105 update deps in monorepo template
  packages/create/src/templates.json
Labels: patch

#107 gracefully handle no git user set
  packages/create/src/run.ts
Labels: patch

#111 Size bug
  packages/eslint-config/index.js
  plugins/size/src/index.ts
Labels: patch

#113 Edit ts linting rule
  packages/eslint-config/index.js
Labels: patch
