Repository intuit/design-systems-cli, pull requests merged in 2021-03, with the labels that each got.

#633 use version in babel runtime for bundle size wins
  plugins/build/src/configs/babel.config.ts
Labels: patch

#634 turn off side effects for utils
  packages/utils/package.json
Labels: patch

#636 add babel plugin macros to default build config
  plugins/build/package.json
  plugins/build/src/configs/babel.config.ts
  yarn.lock
Labels: minor

#637 update renovate config
  renovate.json
Labels: internal

#639 add concurrency limit
  renovate.json
Labels: internal

#640 add renovate schedule
  renovate.json
Labels: internal

#547 Add Contributing Guide #531
  CONTRIBUTING.md
Labels: documentation

#561 docs: update installation guide and add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#643 upgrade eslint-plugin-react-hooks
  packages/eslint-config/package.json
  yarn.lock
Labels: patch

#644 add command to run all tests synchronous
  plugins/test/src/command.ts
  plugins/test/src/index.ts
Labels: minor

#646 add react element as optional type in styled component
  packages/utils/README.md
  packages/utils/package.json
  packages/utils/src/utils/styled.tsx
Labels: minor
