Repository intuit/design-systems-cli, pull requests merged in 2022-05, with the labels that each got.

#692 Add "fill" icon option & expand invalid attributes regex for svg-icon-builder
  packages/svg-icon-builder/README.md
  packages/svg-icon-builder/package.json
  packages/svg-icon-builder/src/index.ts
  packages/svg-icon-builder/svg/data.svg
Labels: minor

#667 remove bin from core package because it doesn't exist
  packages/core/package.json
Labels: patch, skip-release

#699 Guard against `window` not existing in test setup
  plugins/test/src/jest/setupTests.ts
Labels: patch
